
import 'bootstrap/dist/css/bootstrap.css'
import "./globals.css";
import BootstrapClient from './components/BootstrapClient';
import Navbar from './components/navbar';
import { Poppins } from 'next/font/google';
import { Inter } from 'next/font/google';
import FooterComponent from './components/footer';
import FooterWrapper from './components/FooterWrapper';


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // You can include any weights you need
  variable: '--font-poppins',    // Optional: CSS variable
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <Navbar />
        {children}
        <FooterWrapper/>
        <BootstrapClient />
      </body>
    </html>
  );
}
