import 'bootstrap/dist/css/bootstrap.css'
import "./globals.css";
import BootstrapClient from './components/BootstrapClient';
import Navbar from './components/navbar';
import { Poppins } from 'next/font/google';
import { Inter } from 'next/font/google';
import FooterWrapper from './components/FooterWrapper';
import NavbarWrapper from './components/NavbarWrapper';
import UseAuth from './hooks/useAuth';



const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // You can include any weights you need
  variable: '--font-poppins',    // Optional: CSS variable
})
export const metadata = {
  title: "M.O.D Supervision Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body className={`${poppins.className}`}>
        <UseAuth/>
        <NavbarWrapper />
        {children}
        <FooterWrapper />
        <BootstrapClient />
      </body>
    </html>
  );
}
